{% set name = "kantoku" %}
{% set version = "0.18.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kantoku-{{ version }}.tar.gz
  sha256: 751882b2bde074cd8d65f8f9f62606a805b7aa9ea956ba452d13fab0352b5163

build:
  entry_points:
    - circusd = circus.circusd:main
    - circusd-stats = circus.stats:main
    - circusctl = circus.circusctl:main
    - circus-top = circus.stats.client:main
    - circus-plugin = circus.plugins:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.4,<4
    - pip
  run:
    - python >={{ python_min }}
    - psutil
    - pyzmq >=17.0
    - tornado >=5.0.2
    - __unix  # [unix]
    - __win   # [win]
    - ncurses  # [unix]

test:
  imports:
    - circus
  commands:
    - pip check
    - circusd --help  # [unix]
    - circusd-stats --help  # [unix]
    - circusctl --help  # [unix]
    - circus-top --help  # [unix]
    - circus-plugin --help  # [unix]
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Circus is a program that will let you run and watch multiple processes and sockets.
  dev_url: https://github.com/bentoml/kantoku
  home: https://circus.readthedocs.io/en/latest/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
